#!/bin/bash

echo "🎨 Starting Auditor Slide Generator Plugin Development"
echo "=================================================="

echo "✅ Plugin ready for testing!"
echo ""
echo "📋 Next Steps:"
echo "1. Open Figma in your browser"
echo "2. Go to Plugins → Development → Import plugin from manifest..."
echo "3. Select the manifest.json file from this directory"
echo "4. Start using the plugin!"
echo ""
echo "🔧 Plugin Architecture:"
echo "  Main Thread (code.js): Figma document manipulation"
echo "  iframe UI (ui.html): External API calls & user interface"
echo "  Message passing between main thread and iframe"
echo ""
echo "🌐 External Dependencies:"
echo "  - Sherlock scraper API running on localhost:5000"
echo "  - Profile image URLs from Sherlock CDN"
echo ""
echo "📖 See README.md for detailed usage instructions"